version: "3.7"
services:
  upload_app:
    container_name: upload_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_vol:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

volumes:
  app_vol:
