version: "3.7"
services:
  upload_app:
    image: mohammedwazier/upload_app:latest
    restart: always
    volumes:
      - app_vol:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
volumes:
  app_vol:
